USER_AGREEMENT_TEXT = {
    "ru": (
        "📄 *Пользовательское соглашение и Политика конфиденциальности Cragsy*\n"
        "*Дата вступления в силу:* 24 апреля 2025 г.\n"
        "*Дата обновления:* 23 ноября 2025 г.\n\n"

        "Настоящий документ (далее — «Соглашение») регулирует порядок использования Telegram-бота Cragsy "
        "(далее — «Платформа») и одновременно содержит условия Политики конфиденциальности, регулирующие "
        "обработку данных Пользователей. Используя Платформу, вы подтверждаете, что вам исполнилось 18 лет и вы "
        "полностью принимаете условия настоящего Соглашения.\n\n"

        "*1. Общие положения*\n"
        "1.1. Платформа является техническим сервисом для поиска напарников по скалолазанию, общения и размещения "
        "объявлений. Платформа не является туроператором, тренером, страховой компанией, медицинской организацией "
        "или организатором спортивных мероприятий.\n"
        "1.2. Платформа функционирует внутри мессенджера Telegram. Обработка данных самим Telegram регулируется его "
        "документами. Администрация Платформы (далее — «Администрация») не контролирует работу Telegram и не несёт "
        "ответственности за его сбои, ограничения и политику обработки данных.\n"
        "1.3. Использование Платформы возможно только при полном согласии с настоящим Соглашением. Если вы не "
        "согласны с каким-либо условием, вы обязаны прекратить использование Платформы и удалить свою анкету.\n\n"

        "*2. Возрастные ограничения и акцепт*\n"
        "2.1. Регистрируясь и используя Платформу, вы подтверждаете, что вам исполнилось 18 лет и вы обладаете "
        "необходимой дееспособностью по законам своей страны.\n"
        "2.2. Администрация не обязана проверять возраст, личность или полномочия Пользователей, но вправе ограничить "
        "доступ при подозрении на нарушения.\n"
        "2.3. Продолжение использования Платформы после обновления Соглашения означает ваше согласие с новой редакцией.\n\n"

        "*3. Регистрация, аккаунт и ответственность Пользователя*\n"
        "3.1. Доступ к Платформе осуществляется через ваш Telegram-аккаунт. Telegram ID используется как "
        "технический идентификатор.\n"
        "3.2. Вы обязуетесь предоставлять достоверные и актуальные данные в анкете (имя, город, уровень и тип "
        "лазания, пол, при желании — вес и био, фото и др.).\n"
        "3.3. Вы несёте полную ответственность за безопасность своего Telegram-аккаунта и не должны передавать "
        "доступ третьим лицам. Все действия, совершённые через ваш аккаунт, считаются совершёнными лично вами, "
        "пока не будет доказано обратное.\n\n"

        "*4. Правила поведения и запрещённое использование*\n"
        "4.1. Платформа предназначена для поиска напарников, общения и совместных тренировок. Пользователю запрещается:\n"
        "- размещать заведомо ложную, вводящую в заблуждение, оскорбительную, дискриминационную или незаконную информацию;\n"
        "- публиковать порнографический контент, материалы с участием несовершеннолетних, сцены насилия или жестокости;\n"
        "- распространять материалы, содержащие призывы к насилию, терроризму, экстремизму, разжиганию ненависти, "
        "а также рекламу или инструкции по употреблению/изготовлению наркотиков;\n"
        "- использовать чужие фотографии, тексты и иной контент без необходимых прав;\n"
        "- размещать спам, мошеннические схемы, вирусы, вредоносный код, пытаться взломать или нарушить работу Платформы;\n"
        "- использовать Платформу для массовых рассылок без разрешения Администрации;\n"
        "- размещать прямые контакты (телефоны, e-mail, ссылки на другие соцсети/мессенджеры и т.п.) в случаях, "
        "когда это прямо запрещено интерфейсом.\n"
        "4.2. Нарушение указанных правил может привести к ограничению функционала, изоляции профиля из поиска, "
        "временной или постоянной блокировке, удалению анкеты без какой-либо компенсации.\n\n"

        "*5. Офлайн-встречи и отказ от ответственности*\n"
        "5.1. Платформа предоставляет только техническую возможность для знакомства и обмена сообщениями между "
        "Пользователями. Администрация не проверяет личность, репутацию, квалификацию, опыт скалолазания, намерения "
        "и иные характеристики Пользователей.\n"
        "5.2. Все офлайн-встречи, тренировки, выезды на скалы, соревнования и любая другая активность происходят "
        "исключительно по вашей инициативе и на ваш собственный риск.\n"
        "5.3. Администрация не несёт ответственности за любые события, произошедшие до, во время или после "
        "встречи Пользователей, включая, но не ограничиваясь, травмами, ущербом имуществу, финансовыми потерями, "
        "моральным вредом и иными последствиями.\n"
        "5.4. Вы обязаны самостоятельно оценивать риски, использовать разумные меры предосторожности и соблюдать "
        "правила безопасного скалолазания и техники безопасности.\n\n"

        "*6. Чаты, переписка и коммуникация*\n"
        "6.1. Общение между Пользователями может осуществляться через прокси-чаты: Платформа пересылает сообщения, "
        "скрывая реальные контакты (username/номер телефона), пока вы сами не раскроете их другому Пользователю.\n"
        "6.2. Платформа хранит историю переписок и связанных с ними технических данных в целях обеспечения работы "
        "чатов, модерации, рассмотрения жалоб, предотвращения нарушений и защиты прав Платформы и Пользователей.\n"
        "6.3. Раскрытие вами своих контактов в переписке (телефон, социальные сети и т.п.) происходит по вашей "
        "инициативе и находится под вашей полной ответственностью.\n"
        "6.4. Администрация вправе ограничивать, останавливать или завершать чаты, скрывать или удалять отдельные "
        "сообщения и диалоги, если сочтёт это необходимым для безопасности или соблюдения закона.\n"
        "6.5. Администрация не несёт ответственности за содержание сообщений, высказывания, предложения и любые "
        "решения, которые вы принимаете на основании переписки.\n\n"

        "*7. Контент Пользователя*\n"
        "7.1. Пользователь сохраняет права на размещаемый им контент (фото, описание анкеты, объявления и т.п.) и "
        "несёт полную ответственность за его соответствие закону, настоящему Соглашению и правам третьих лиц.\n"
        "7.2. Размещая контент, Пользователь:\n"
        "- подтверждает, что обладает всеми необходимыми правами на такой контент;\n"
        "- предоставляет Администрации безвозмездную, неисключительную, действующую по всему миру лицензию на его "
        "использование в рамках работы Платформы: показ в анкетах, поиске, чатах, объявлениях, внутренней аналитике, "
        "модерации и демонстрации интерфейса (например, скриншоты, промо-материалы) без указания имени, если иное "
        "не согласовано отдельно.\n"
        "7.3. Администрация вправе автоматически и вручную модерировать контент, а также удалять или скрывать его, "
        "если сочтёт, что он нарушает закон, настоящее Соглашение или наносит вред Платформе и Пользователям.\n\n"

        "*8. Политика конфиденциальности (Privacy Policy)*\n"
        "8.1. Платформа обрабатывает только те данные, которые необходимы для её функционирования, безопасности и "
        "улучшения сервиса. В частности, могут обрабатываться:\n"
        "- Telegram ID, username, язык интерфейса;\n"
        "- данные анкеты (имя, город, страна, уровень и тип лазания, пол, вес при указании, статус, био, фотографии);\n"
        "- лайки, жалобы, просмотры, матчи, действия в интерфейсе;\n"
        "- объявления в разделе встреч;\n"
        "- сообщения и история переписок внутри Платформы;\n"
        "- данные о виртуальной \"магнезии\", Boost, реферальных механиках, подписках и покупках внутри Платформы;\n"
        "- технические логи (даты входа, активность, базовые события в боте).\n\n"
        "8.2. Данные хранятся в защищённой базе данных (например, PostgreSQL), размещённой на облачном хостинге, "
        "который используется исключительно для технического обеспечения работы Платформы.\n"
        "8.3. Основные цели обработки данных:\n"
        "- обеспечение работы Платформы и её функций (поиск напарников, чаты, объявления);\n"
        "- поддержание безопасности и предотвращение злоупотреблений, спама, мошенничества и нарушений;\n"
        "- обработка жалоб и модерация контента;\n"
        "- внутренняя аналитика и улучшение сервиса;\n"
        "- учёт виртуальной магнезии, реферальных механик, платных функций и подписок;\n"
        "- выполнение требований применимого законодательства при наличии таких обязанностей.\n"
        "8.4. Данные не продаются и не передаются сторонним рекламодателям. Доступ к ним может быть предоставлен "
        "только ограниченному кругу лиц, действующих по поручению Администрации, а также в случаях, прямо "
        "предусмотренных законом.\n"
        "8.5. При активном профиле данные хранятся до тех пор, пока вы пользуетесь Платформой. После удаления "
        "анкеты основные данные профиля удаляются или анонимизируются в разумные сроки. При этом отдельные категории "
        "данных могут сохраняться на более длительный или неопределённый срок при наличии законных оснований, в том числе:\n"
        "- жалобы, история нарушений и баны;\n"
        "- данные о виртуальной магнезии, реферальных действиях, платных активациях и подписках;\n"
        "- технические логи, необходимые для безопасности и предотвращения злоупотреблений;\n"
        "- фрагменты переписок, относящиеся к жалобам или нарушениям.\n"
        "Это необходимо для защиты Платформы и Пользователей, предотвращения повторной регистрации нарушителей, "
        "ведения статистики и соблюдения требований закона.\n"
        "8.6. Платформа не обрабатывает и не хранит данные банковских карт и иных платёжных инструментов — они "
        "обрабатываются Telegram и/или его платёжными партнёрами.\n\n"

        "*9. Виртуальная \"магнезия\" и внутренняя активность*\n"
        "9.1. Внутри Платформы может использоваться условная виртуальная единица — \"магнезия\" (граммы магнезии), "
        "начисляемая за действия Пользователя (например, приглашения друзей, размещение объявлений) или получаемая "
        "другими предусмотренными способами.\n"
        "9.2. Магнезия:\n"
        "- не является электронной валютой, платёжным средством, ценной бумагой или финансовым инструментом;\n"
        "- не имеет фиксированной стоимости в реальных деньгах;\n"
        "- не может быть выведена, продана, обменена на фиат, криптовалюту или иные активы вне Платформы;\n"
        "- может быть использована только на функции внутри Платформы (например, Boost и другие опции).\n"
        "9.3. Администрация вправе менять правила начисления и расходования магнезии, а также корректировать или "
        "обнулять баланс в случае ошибок, багов, злоупотреблений или нарушений.\n\n"

        "*10. Telegram Stars, платные функции и отсутствие возвратов*\n"
        "10.1. Отдельные функции Платформы (включая покупку магнезии, Boost, особые статусы и т.п.) могут "
        "оплачиваться через Telegram Stars и другие механизмы, предоставляемые Telegram.\n"
        "10.2. Покупка Telegram Stars осуществляется у Telegram и/или его партнёров по их правилам. Платформа "
        "не хранит и не обрабатывает платёжные реквизиты Пользователей.\n"
        "10.3. Списание Telegram Stars за платные функции Платформы является окончательным. *Возврат Telegram Stars "
        "за платные услуги Платформы Администрацией не производится* ни при каких обстоятельствах, включая, но не "
        "ограничиваясь: удалением анкеты, баном, изменением функционала, техническими сбоями Telegram или "
        "прекращением работы Платформы.\n"
        "10.4. Платные функции считаются оказанными с момента их активации в боте, независимо от того, пользовались "
        "вы ими фактически или нет.\n\n"

        "*11. Модерация, жалобы и санкции*\n"
        "11.1. Пользователь может пожаловаться на другого Пользователя или контент через встроенный функционал.\n"
        "11.2. Администрация вправе применять любые предусмотренные меры: предупреждения, временную изоляцию из "
        "поиска, ограничения функционала, бан, удаление анкеты и связанного контента.\n"
        "11.3. Жалобы и связанные с ними данные (включая информацию о нарушениях, баны, фрагменты переписок) "
        "могут храниться длительное или неопределённое время при наличии законных оснований, чтобы предотвращать "
        "повторные нарушения и обеспечивать безопасность сообщества.\n"
        "11.4. Администрация не обязана раскрывать детали работы антиспам- и антифрод-систем, а также внутреннюю "
        "логику принятия решений о санкциях.\n\n"

        "*12. Ограничение ответственности*\n"
        "12.1. Платформа предоставляется по принципу \"как есть\" (\"as is\"), без каких-либо явных или "
        "подразумеваемых гарантий, включая, но не ограничиваясь: бесперебойной работой, соответствием вашим "
        "ожиданиям, наличием достаточного числа Пользователей в вашем городе, достижением конкретного результата.\n"
        "12.2. В максимально возможной степени, допускаемой применимым правом, Администрация не несёт ответственности за:\n"
        "- прямые или косвенные убытки, упущенную выгоду, потерю данных, репутационный ущерб;\n"
        "- поведение других Пользователей онлайн и офлайн;\n"
        "- достоверность информации в анкетах, объявлениях и сообщениях;\n"
        "- сбои Telegram, ограничение доступа, удаление сообщений и медиа самим мессенджером;\n"
        "- любые решения и действия, которые вы совершаете на основе информации из Платформы.\n"
        "12.3. Если какое-либо ограничение ответственности будет признано недействительным, это не влияет на "
        "действительность остальных положений.\n\n"

        "*13. Изменения Соглашения*\n"
        "13.1. Администрация вправе в одностороннем порядке изменять настоящее Соглашение.\n"
        "13.2. Обновлённая редакция может быть отображена в интерфейсе бота. Продолжая использовать Платформу после "
        "обновления, вы подтверждаете согласие с новой редакцией.\n"
        "13.3. Если вы не согласны с изменениями, вы должны прекратить использование Платформы и удалить анкету.\n\n"

        "*14. Применимое право и споры*\n"
        "14.1. К настоящему Соглашению может применяться право государства местонахождения Администрации и/или "
        "иное применимое право согласно коллизионным нормам.\n"
        "14.2. По возможности споры разрешаются путём переговоров. При невозможности договориться спор подлежит "
        "рассмотрению в компетентном суде по месту нахождения Администрации, если иное не предусмотрено "
        "императивными нормами применимого права.\n\n"

        "*15. Контакт с Администрацией*\n"
        "Все вопросы, запросы и обращения по работе Платформы и настоящему Соглашению принимаются *исключительно* "
        "через встроенный раздел Отзыв внутри Платформы. Иные каналы связи могут не рассматриваться.\n"
    ),   

    "en": (
        "📄 *Cragsy User Agreement & Privacy Policy*\n"
        "*Effective date:* April 24, 2025\n"
        "*Last updated:* November 23, 2025\n\n"

        "This document (the \"Agreement\") governs your use of the Cragsy Telegram bot (the \"Platform\") "
        "and also contains the Privacy Policy regulating the processing of user data. By using the Platform, "
        "you confirm that you are at least 18 years old and fully accept the terms of this Agreement.\n\n"

        "*1. General Provisions*\n"
        "1.1. The Platform is a technical service for finding climbing partners, communicating, and posting meetups. "
        "It is not a tour operator, coach, insurance provider, medical institution, or organizer of sports events.\n"
        "1.2. The Platform operates within the Telegram messenger. All data processed by Telegram is governed by "
        "Telegram’s own policies. The Platform Administration (the \"Administration\") does not control Telegram’s "
        "operations and is not responsible for its outages, restrictions, or privacy practices.\n"
        "1.3. Use of the Platform is possible only upon full acceptance of this Agreement. If you do not agree with "
        "any provision, you must stop using the Platform and delete your profile.\n\n"

        "*2. Age Restrictions & Acceptance*\n"
        "2.1. By registering and using the Platform, you confirm that you are at least 18 years old and possess full "
        "legal capacity according to the laws of your country.\n"
        "2.2. The Administration is not obliged to verify users' age or identity but may restrict access if violations "
        "are suspected.\n"
        "2.3. Continued use of the Platform after updates to this Agreement constitutes your acceptance of the new version.\n\n"

        "*3. Registration, Account & User Responsibility*\n"
        "3.1. Access to the Platform is provided through your Telegram account. Your Telegram ID is used as a technical identifier.\n"
        "3.2. You agree to provide accurate and up-to-date information (name, city, climbing level, climbing type, gender, "
        "optional weight, bio, and profile photo).\n"
        "3.3. You are fully responsible for the security of your Telegram account. All actions performed through your account "
        "are considered performed by you unless proven otherwise.\n\n"

        "*4. Rules of Conduct & Prohibited Use*\n"
        "4.1. The Platform is intended for partner search and communication. You are prohibited from posting:\n"
        "- knowingly false, misleading, offensive, discriminatory, or unlawful information;\n"
        "- pornographic content, materials involving minors, or graphic violence;\n"
        "- content promoting violence, terrorism, extremism, hatred, or drug use/production;\n"
        "- spam, scams, malware, or attempts to hack or disrupt the Platform;\n"
        "- photos, texts, or other content you do not own the rights to;\n"
        "- direct contact details (phone numbers, emails, links to other social networks/messengers) where prohibited.\n"
        "4.2. Violations may result in restricted functionality, isolation from search, temporary or permanent bans, "
        "or deletion of your profile without compensation.\n\n"

        "*5. Offline Meetings & Liability Disclaimer*\n"
        "5.1. The Platform only provides a technical tool for meeting other users. The Administration does not verify users’ "
        "identity, intentions, reliability, climbing experience, or qualifications.\n"
        "5.2. All offline meetings, training sessions, climbing trips, or any other activities occur solely at your own risk.\n"
        "5.3. The Administration bears no responsibility for any events occurring before, during, or after user meetings, "
        "including injuries, property damage, financial loss, or other consequences.\n"
        "5.4. You must independently assess risks, take reasonable precautions, and follow climbing safety rules.\n\n"

        "*6. Chats, Messaging & Communication*\n"
        "6.1. Messaging between users may occur via proxy-chat: messages are relayed through the Platform while hiding "
        "real contact information.\n"
        "6.2. The Platform stores chat history and related technical data to ensure chat functionality, moderation, "
        "complaint handling, and prevention of abuse.\n"
        "6.3. If you voluntarily disclose your contact details in a chat, you bear full responsibility for doing so.\n"
        "6.4. The Administration may restrict or terminate chats, hide or delete messages if necessary for safety or legal compliance.\n"
        "6.5. The Administration is not responsible for the content of user messages or decisions made based on conversations.\n\n"

        "*7. User Content*\n"
        "7.1. You retain rights to your uploaded content but are fully responsible for its legality and compliance.\n"
        "7.2. By posting content, you:\n"
        "- confirm that you hold all necessary rights to such content;\n"
        "- grant the Administration a worldwide, non-exclusive, royalty-free license to use it within the Platform "
        "(profiles, search, chats, listings, analytics, moderation, and interface demonstrations) without naming you unless agreed otherwise.\n"
        "7.3. The Administration may moderate, hide, or delete content violating this Agreement or harming the Platform.\n\n"

        "*8. Privacy Policy*\n"
        "8.1. The Platform processes only data necessary for operation, safety, and service improvement. This includes:\n"
        "- Telegram ID, username, language;\n"
        "- profile data (name, city, country, climbing level/type, gender, optional weight, status, bio, photos);\n"
        "- likes, reports, views, matches, interactions;\n"
        "- meetup posts;\n"
        "- messages and chat history;\n"
        "- virtual chalk (magnesia), Boost usage, referrals, internal subscriptions, purchases;\n"
        "- technical logs (login dates, key actions).\n\n"
        "8.2. Data is stored in a secure database (PostgreSQL) hosted on a cloud provider used strictly for technical operation.\n"
        "8.3. Main purposes of data processing:\n"
        "- operating the Platform and its features;\n"
        "- ensuring safety and preventing fraud or abuse;\n"
        "- handling complaints and moderating content;\n"
        "- internal analytics and service improvement;\n"
        "- maintaining magnesia, referrals, paid features, and subscriptions systems;\n"
        "- complying with applicable legal obligations.\n"
        "8.4. Data is *not* sold or shared with advertisers. Access is limited to authorized personnel and lawful requests.\n"
        "8.5. When your profile is deleted, your primary profile data is deleted or anonymized within a reasonable timeframe. "
        "However, certain categories of data may be stored for an extended or indefinite period where lawful and necessary, including:\n"
        "- reports, violation history, bans;\n"
        "- virtual chalk history, referrals, purchases, internal subscription data;\n"
        "- technical logs required for safety and abuse prevention;\n"
        "- specific chat fragments linked to complaints.\n"
        "This is required to protect the Platform and users, prevent repeated violations, maintain statistics, and comply with law.\n"
        "8.6. The Platform does not store or process credit card information — all payments are handled by Telegram.\n\n"

        "*9. Virtual Chalk (Magnesia)*\n"
        "9.1. The Platform uses a virtual in-app unit called \"magnesia\" (grams of chalk), earned or obtained through actions "
        "or internal mechanics.\n"
        "9.2. Magnesia:\n"
        "- is not electronic money or a financial instrument;\n"
        "- has no monetary value outside the Platform;\n"
        "- cannot be withdrawn, sold, or converted into fiat/crypto;\n"
        "- may only be used for in-Platform features (e.g., Boost).\n"
        "9.3. The Administration may modify magnesia rules and adjust balances in case of bugs, errors, or abuse.\n\n"

        "*10. Telegram Stars, Paid Features & No Refunds*\n"
        "10.1. Paid features (magnesia purchases, Boost, Founder status, etc.) may be purchased via Telegram Stars.\n"
        "10.2. Stars are purchased from Telegram or its partners. The Platform does not store financial data.\n"
        "10.3. Deduction of Telegram Stars is *final and non-refundable*. The Administration does not refund Stars under "
        "any circumstances, including account deletion, bans, feature changes, Telegram issues, or Platform shutdown.\n"
        "10.4. Paid features are considered delivered once activated, regardless of actual usage.\n\n"

        "*11. Moderation, Reports & Sanctions*\n"
        "11.1. Users may report others via built-in tools.\n"
        "11.2. The Administration may apply any moderation measures: warnings, isolation from search, feature limits, bans, "
        "or profile deletion.\n"
        "11.3. Reports, violation data, bans, and related chat fragments may be stored indefinitely where legally justified, "
        "to prevent repeat abuse and ensure community safety.\n"
        "11.4. The Administration is not required to disclose moderation logic or internal anti-abuse systems.\n\n"

        "*12. Limitation of Liability*\n"
        "12.1. The Platform is provided \"as is\", without warranties of any kind, including continuous availability, "
        "specific results, or suitability for your city.\n"
        "12.2. To the maximum extent permitted by law, the Administration is not liable for:\n"
        "- direct or indirect damages, lost data, lost profit, reputational harm;\n"
        "- actions of other users online or offline;\n"
        "- accuracy of user profiles or listings;\n"
        "- outages or limitations of Telegram;\n"
        "- any decisions you make based on information received via the Platform.\n\n"

        "*13. Agreement Changes*\n"
        "13.1. The Administration may update this Agreement at any time.\n"
        "13.2. The updated version may be shown inside the bot. Continued use constitutes acceptance.\n"
        "13.3. If you do not agree with changes, you must stop using the Platform and delete your profile.\n\n"

        "*14. Governing Law & Disputes*\n"
        "14.1. Governing law may be the law of the country where the Administration is located, or otherwise applicable law.\n"
        "14.2. Disputes should first be resolved through negotiation. If unresolved, disputes shall be handled by a competent "
        "court in the jurisdiction of the Administration unless mandatory law provides otherwise.\n\n"

        "*15. Contact*\n"
        "All questions and requests are accepted *exclusively* through the built-in Feedback section within the Platform. "
        "Other communication channels may not be processed.\n"
    ),
    
    "es": (
        "📄 *Acuerdo de Usuario y Política de Privacidad de Cragsy*\n"
        "*Fecha de entrada en vigor:* 24 de abril de 2025\n"
        "*Última actualización:* 23 de noviembre de 2025\n\n"

        "Este documento (el \"Acuerdo\") regula el uso del bot de Telegram Cragsy (la \"Plataforma\") y contiene "
        "también la Política de Privacidad que regula el tratamiento de los datos de los usuarios. Al utilizar la "
        "Plataforma, usted confirma que tiene al menos 18 años y acepta plenamente los términos de este Acuerdo.\n\n"

        "*1. Disposiciones generales*\n"
        "1.1. La Plataforma es un servicio técnico para encontrar compañeros de escalada, comunicarse y publicar "
        "anuncios de entrenamientos. No es un operador turístico, entrenador, proveedor de seguros, entidad médica "
        "ni organizador de eventos deportivos.\n"
        "1.2. La Plataforma funciona dentro del mensajero Telegram. Todos los datos procesados por Telegram se rigen "
        "por sus propias políticas. La Administración de la Plataforma (la \"Administración\") no controla el "
        "funcionamiento de Telegram ni es responsable de sus fallos, restricciones o políticas de privacidad.\n"
        "1.3. El uso de la Plataforma es posible únicamente tras aceptar plenamente este Acuerdo. Si no está de "
        "acuerdo con alguna condición, debe dejar de usar la Plataforma y eliminar su perfil.\n\n"

        "*2. Restricciones de edad y aceptación*\n"
        "2.1. Al registrarse y utilizar la Plataforma, usted confirma que tiene al menos 18 años y posee plena capacidad "
        "legal según las leyes de su país.\n"
        "2.2. La Administración no está obligada a verificar la edad o identidad de los usuarios, pero podrá "
        "restringir el acceso si se detectan violaciones.\n"
        "2.3. El uso continuado de la Plataforma después de las actualizaciones del Acuerdo implica la aceptación "
        "de la nueva versión.\n\n"

        "*3. Registro, cuenta y responsabilidad del usuario*\n"
        "3.1. El acceso a la Plataforma se realiza a través de su cuenta de Telegram. Su Telegram ID se utiliza como "
        "identificador técnico.\n"
        "3.2. Usted se compromete a proporcionar información precisa y actualizada (nombre, ciudad, nivel de escalada, "
        "tipo de escalada, género, peso opcional, biografía y foto del perfil).\n"
        "3.3. Usted es plenamente responsable de la seguridad de su cuenta de Telegram. Todas las acciones realizadas "
        "a través de su cuenta se consideran realizadas por usted, salvo prueba en contrario.\n\n"

        "*4. Normas de conducta y uso prohibido*\n"
        "4.1. La Plataforma está destinada a la búsqueda de compañeros y comunicación. Está prohibido publicar:\n"
        "- información falsa, engañosa, ofensiva, discriminatoria o ilegal;\n"
        "- contenido pornográfico, material que involucre a menores o violencia explícita;\n"
        "- contenido que promueva violencia, terrorismo, extremismo, odio o drogas;\n"
        "- spam, estafas, malware o intentos de hackeo;\n"
        "- fotos, textos u otro contenido sin los derechos correspondientes;\n"
        "- datos de contacto directo donde esté prohibido por la interfaz.\n"
        "4.2. Las infracciones pueden resultar en restricciones de funciones, aislamiento del perfil en búsquedas, "
        "bloqueo temporal o permanente, o eliminación del perfil sin compensación alguna.\n\n"

        "*5. Encuentros presenciales y exención de responsabilidad*\n"
        "5.1. La Plataforma solo proporciona un medio técnico para conectar usuarios. La Administración no verifica la "
        "identidad, intenciones, fiabilidad, experiencia en escalada ni cualificaciones de los usuarios.\n"
        "5.2. Todas las reuniones presenciales, entrenamientos, salidas a roca u otras actividades se realizan "
        "exclusivamente bajo su propia responsabilidad.\n"
        "5.3. La Administración no es responsable de eventos ocurridos antes, durante o después de los encuentros entre "
        "usuarios, incluyendo lesiones, daños materiales, pérdidas económicas u otras consecuencias.\n"
        "5.4. Usted debe evaluar riesgos, tomar precauciones razonables y seguir las normas de seguridad en escalada.\n\n"

        "*6. Chats, mensajería y comunicación*\n"
        "6.1. La mensajería puede realizarse mediante chats proxy, donde la Plataforma oculta los datos de contacto "
        "reales.\n"
        "6.2. La Plataforma almacena el historial de chats y datos técnicos para garantizar la funcionalidad, moderación, "
        "gestión de reportes y prevención de abusos.\n"
        "6.3. Si usted revela voluntariamente sus contactos en un chat, asume plena responsabilidad.\n"
        "6.4. La Administración podrá limitar o finalizar chats, ocultar o eliminar mensajes cuando sea necesario por "
        "seguridad o cumplimiento legal.\n"
        "6.5. La Administración no es responsable del contenido de los mensajes ni de decisiones tomadas basadas en ellos.\n\n"

        "*7. Contenido del usuario*\n"
        "7.1. Usted conserva los derechos de su contenido, pero es plenamente responsable de su legalidad.\n"
        "7.2. Al publicar contenido, usted:\n"
        "- confirma que posee los derechos necesarios;\n"
        "- concede a la Administración una licencia mundial, no exclusiva y gratuita para usar dicho contenido dentro "
        "de la Plataforma (perfiles, búsqueda, chats, anuncios, analítica, moderación y demostraciones de interfaz) "
        "sin mencionar su nombre salvo acuerdo específico.\n"
        "7.3. La Administración puede moderar, ocultar o eliminar contenido que infrinja este Acuerdo o perjudique la Plataforma.\n\n"

        "*8. Política de privacidad*\n"
        "8.1. La Plataforma procesa únicamente los datos necesarios para su funcionamiento, seguridad y mejora. "
        "Esto incluye:\n"
        "- Telegram ID, username e idioma;\n"
        "- datos del perfil (nombre, ciudad, país, nivel/tipo de escalada, género, peso opcional, estado, bio, fotos);\n"
        "- 'likes', reportes, visualizaciones, coincidencias, acciones;\n"
        "- publicaciones en el panel de encuentros;\n"
        "- mensajes e historial de chats;\n"
        "- datos de magnesia (tiza virtual), Boost, referidos, compras y suscripciones internas;\n"
        "- registros técnicos (fechas de acceso, acciones principales).\n\n"
        "8.2. Los datos se almacenan en una base de datos segura (PostgreSQL) alojada en un proveedor en la nube "
        "utilizado exclusivamente con fines técnicos.\n"
        "8.3. Finalidades principales del tratamiento:\n"
        "- funcionamiento de la Plataforma y sus funciones;\n"
        "- seguridad, prevención de fraude y abusos;\n"
        "- gestión de reportes y moderación;\n"
        "- analítica interna y mejora del servicio;\n"
        "- mantenimiento de magnesia, referidos, funciones de pago y suscripciones;\n"
        "- cumplimiento de obligaciones legales cuando corresponda.\n"
        "8.4. Los datos *no* se venden ni se comparten con anunciantes. El acceso está restringido a personal autorizado "
        "y a solicitudes legales.\n"
        "8.5. Al eliminar su perfil, sus datos principales se eliminan o anonimizan en un plazo razonable. "
        "Sin embargo, ciertas categorías pueden conservarse durante un período prolongado o indefinido cuando sea "
        "legal y necesario, incluyendo:\n"
        "- reportes, historial de infracciones y bloqueos;\n"
        "- historial de magnesia, referidos, compras y suscripciones internas;\n"
        "- registros técnicos requeridos para seguridad y prevención de abusos;\n"
        "- fragmentos de chats vinculados a reportes.\n"
        "Esto es necesario para proteger la Plataforma, evitar reincidencias y cumplir con la ley.\n"
        "8.6. La Plataforma no procesa datos de tarjetas bancarias; los pagos son gestionados por Telegram.\n\n"

        "*9. Magnesia virtual (tiza)*\n"
        "9.1. La Plataforma utiliza una unidad virtual llamada \"magnesia\".\n"
        "9.2. La magnesia:\n"
        "- no es dinero electrónico ni instrumento financiero;\n"
        "- no tiene valor fuera de la Plataforma;\n"
        "- no puede retirarse, venderse ni convertirse en dinero o criptomoneda;\n"
        "- solo puede usarse para funciones internas.\n"
        "9.3. La Administración puede modificar las reglas y ajustar saldos en caso de errores o abusos.\n\n"

        "*10. Telegram Stars, funciones de pago y ausencia de reembolsos*\n"
        "10.1. Algunas funciones de la Plataforma pueden pagarse mediante Telegram Stars.\n"
        "10.2. Las Stars se compran a Telegram o a sus socios; la Plataforma no almacena datos financieros.\n"
        "10.3. La deducción de Stars es *final y no reembolsable*. La Administración no realiza reembolsos bajo "
        "ninguna circunstancia, incluyendo eliminación del perfil, bloqueos, fallos de Telegram o cierre del servicio.\n"
        "10.4. Las funciones de pago se consideran entregadas desde el momento de activación.\n\n"

        "*11. Moderación, reportes y sanciones*\n"
        "11.1. Los usuarios pueden reportar a otros mediante las herramientas integradas.\n"
        "11.2. La Administración puede aplicar cualquier medida: advertencias, aislamiento del perfil, restricciones "
        "de funciones, bloqueos o eliminación del perfil.\n"
        "11.3. Los reportes, infracciones, bloqueos y fragmentos de chats pueden almacenarse por tiempo indefinido "
        "cuando esté legalmente justificado.\n"
        "11.4. La Administración no está obligada a revelar la lógica interna de moderación.\n\n"

        "*12. Limitación de responsabilidad*\n"
        "12.1. La Plataforma se proporciona \"tal cual\" (\"as is\"), sin garantías de ningún tipo.\n"
        "12.2. En la máxima medida permitida por la ley, la Administración no es responsable de:\n"
        "- daños directos o indirectos, pérdida de datos o de beneficios;\n"
        "- acciones de otros usuarios online u offline;\n"
        "- exactitud del contenido publicado por usuarios;\n"
        "- fallos o restricciones de Telegram;\n"
        "- decisiones tomadas basadas en información de la Plataforma.\n\n"

        "*13. Cambios en el Acuerdo*\n"
        "13.1. La Administración puede actualizar este Acuerdo en cualquier momento.\n"
        "13.2. La versión actualizada puede mostrarse en el bot. El uso continuado implica aceptación.\n"
        "13.3. Si no está de acuerdo, debe dejar de usar la Plataforma y eliminar su perfil.\n\n"

        "*14. Ley aplicable y disputas*\n"
        "14.1. Puede aplicarse la ley del país donde se encuentra la Administración u otra ley aplicable.\n"
        "14.2. Las disputas deben resolverse inicialmente mediante negociación. Si no es posible, se remitirán "
        "al tribunal competente según la jurisdicción de la Administración, salvo que la ley disponga lo contrario.\n\n"

        "*15. Contacto*\n"
        "Todas las consultas deben enviarse *exclusivamente* a través de la sección Feedback dentro de la "
        "Plataforma. Otros canales pueden no ser atendidos.\n"
    ),

    "de": (
        "📄 *Cragsy Nutzungsvereinbarung & Datenschutzrichtlinie*\n"
        "*Gültig ab:* 24. April 2025\n"
        "*Zuletzt aktualisiert:* 23. November 2025\n\n"

        "Dieses Dokument (die „Vereinbarung“) regelt die Nutzung des Cragsy-Telegram-Bots (die „Plattform“) und "
        "enthält gleichzeitig die Datenschutzrichtlinie zur Verarbeitung personenbezogener Daten. Durch die Nutzung "
        "der Plattform bestätigen Sie, dass Sie mindestens 18 Jahre alt sind und die Bedingungen dieser Vereinbarung "
        "vollständig akzeptieren.\n\n"

        "*1. Allgemeine Bestimmungen*\n"
        "1.1. Die Plattform ist ein technischer Dienst zur Suche nach Kletterpartnern, zur Kommunikation und zur "
        "Veröffentlichung von Trainings- oder Meetup-Anzeigen. Sie ist kein Reiseveranstalter, Trainer, "
        "Versicherungsanbieter, medizinischer Dienst oder Veranstalter von Sportereignissen.\n"
        "1.2. Die Plattform funktioniert innerhalb des Telegram-Messengers. Alle durch Telegram verarbeiteten Daten "
        "unterliegen den Telegram-Datenschutzrichtlinien. Die Plattformverwaltung (die „Verwaltung“) kontrolliert "
        "Telegram nicht und ist nicht verantwortlich für dessen Ausfälle, Einschränkungen oder Datenschutzpraktiken.\n"
        "1.3. Die Nutzung der Plattform ist nur bei vollständiger Zustimmung zu dieser Vereinbarung zulässig. Wenn Sie "
        "mit irgendeinem Teil nicht einverstanden sind, müssen Sie die Nutzung einstellen und Ihr Profil löschen.\n\n"

        "*2. Altersbeschränkung & Zustimmung*\n"
        "2.1. Durch Registrierung und Nutzung bestätigen Sie, dass Sie mindestens 18 Jahre alt und voll geschäftsfähig "
        "gemäß den Gesetzen Ihres Landes sind.\n"
        "2.2. Die Verwaltung ist nicht verpflichtet, das Alter oder die Identität der Nutzer zu überprüfen, kann jedoch "
        "den Zugang einschränken, wenn Verstöße vermutet werden.\n"
        "2.3. Die fortgesetzte Nutzung nach einer Aktualisierung dieser Vereinbarung bedeutet Ihre Zustimmung zur neuen Version.\n\n"

        "*3. Registrierung, Konto & Verantwortung des Nutzers*\n"
        "3.1. Der Zugriff erfolgt über Ihr Telegram-Konto. Ihre Telegram-ID dient als technischer Identifikator.\n"
        "3.2. Sie verpflichten sich, korrekte und aktuelle Daten bereitzustellen (Name, Stadt, Kletterniveau, "
        "Kletterart, Geschlecht, optionales Gewicht, Biografie, Profilfoto).\n"
        "3.3. Sie sind vollständig für die Sicherheit Ihres Telegram-Kontos verantwortlich. Alle über Ihr Konto "
        "ausgeführten Handlungen gelten als von Ihnen durchgeführt, sofern nicht das Gegenteil bewiesen wird.\n\n"

        "*4. Verhaltensregeln & Verbotene Nutzung*\n"
        "4.1. Die Plattform ist für die Suche nach Kletterpartnern und für Kommunikation vorgesehen. Verboten sind:\n"
        "- falsche, irreführende, beleidigende, diskriminierende oder illegale Inhalte;\n"
        "- pornografische Inhalte, Materialien mit Minderjährigen, Gewalt- oder Misshandlungsszenen;\n"
        "- Inhalte, die Gewalt, Terrorismus, Extremismus, Hass oder Drogen fördern;\n"
        "- Spam, Betrug, Malware oder Versuche, die Plattform zu hacken oder zu stören;\n"
        "- Fotos, Texte oder Inhalte ohne entsprechende Rechte;\n"
        "- direkte Kontaktdaten (Telefonnummern, E-Mails, Links zu anderen Netzwerken), sofern dies untersagt ist.\n"
        "4.2. Verstöße können zu Funktionsbeschränkungen, Such-Isolation, temporären oder permanenten Sperren oder "
        "Profilentfernungen ohne Kompensation führen.\n\n"

        "*5. Offline-Treffen & Haftungsausschluss*\n"
        "5.1. Die Plattform stellt lediglich ein technisches Werkzeug zur Kontaktaufnahme bereit. Die Verwaltung "
        "überprüft nicht Identität, Absichten, Zuverlässigkeit oder Kletterfähigkeiten der Nutzer.\n"
        "5.2. Alle persönlichen Treffen, Trainings, Outdoor-Aktivitäten oder andere Handlungen erfolgen ausschließlich "
        "auf Ihr eigenes Risiko.\n"
        "5.3. Die Verwaltung übernimmt keine Haftung für Ereignisse vor, während oder nach Treffen, einschließlich "
        "Verletzungen, Sachschäden, finanziellen Verlusten oder anderen Folgen.\n"
        "5.4. Sie müssen Risiken selbst einschätzen, Vorsichtsmaßnahmen treffen und Klettersicherheitsregeln befolgen.\n\n"

        "*6. Chats & Kommunikation*\n"
        "6.1. Nachrichtenübertragung erfolgt ggf. über Proxy-Chats, bei denen Ihre realen Kontaktdaten verborgen bleiben.\n"
        "6.2. Die Plattform speichert Chatverläufe und technische Daten zur Funktionssicherung, Moderation, "
        "Missbrauchsprävention und Bearbeitung von Meldungen.\n"
        "6.3. Wenn Sie freiwillig Ihre Kontaktdaten offenlegen, tragen Sie dafür allein die Verantwortung.\n"
        "6.4. Die Verwaltung kann Chats einschränken, beenden, Nachrichten verbergen oder löschen, wenn dies aus "
        "Sicherheits- oder Rechtsgründen erforderlich ist.\n"
        "6.5. Die Verwaltung übernimmt keine Verantwortung für Inhalte von Nutzer Nachrichten oder daraus resultierende Entscheidungen.\n\n"

        "*7. Nutzerinhalte*\n"
        "7.1. Sie behalten die Rechte an Ihren Inhalten, tragen jedoch volle Verantwortung für deren Rechtmäßigkeit.\n"
        "7.2. Durch das Hochladen von Inhalten:\n"
        "- bestätigen Sie, dass Sie die erforderlichen Rechte besitzen;\n"
        "- gewähren Sie der Verwaltung eine weltweite, nicht exklusive, kostenlose Lizenz zur Nutzung innerhalb der Plattform "
        "(Profile, Suche, Chats, Anzeigen, Analysen, Moderation, Interface-Darstellungen), ohne Namensnennung, sofern nicht anders vereinbart.\n"
        "7.3. Die Verwaltung kann Inhalte moderieren, verbergen oder löschen, wenn sie gegen dieses Abkommen verstoßen.\n\n"

        "*8. Datenschutzrichtlinie*\n"
        "8.1. Die Plattform verarbeitet nur Daten, die für den Betrieb, die Sicherheit und die Verbesserung des Dienstes "
        "erforderlich sind, einschließlich:\n"
        "- Telegram ID, Username, Sprache;\n"
        "- Profildaten (Name, Stadt, Land, Kletterniveau/-art, Geschlecht, optionales Gewicht, Status, Bio, Fotos);\n"
        "- Likes, Meldungen, Aufrufe, Matches, Interaktionen;\n"
        "- Meetup-Anzeigen;\n"
        "- Nachrichten & Chatverläufe;\n"
        "- virtuelle Magnesia, Boost-Nutzung, Referal-System, interne Abonnements & Käufe;\n"
        "- technische Logs (Login-Daten, Aktivitäten).\n\n"
        "8.2. Daten werden in einer sicheren PostgreSQL-Datenbank gespeichert, die auf einem Cloud-Provider läuft, der "
        "ausschließlich technische Zwecke erfüllt.\n"
        "8.3. Hauptzwecke der Verarbeitung:\n"
        "- Betrieb der Plattform & Funktionen;\n"
        "- Sicherheit & Missbrauchsprävention;\n"
        "- Bearbeitung von Meldungen & Moderation;\n"
        "- interne Analyse & Verbesserungen;\n"
        "- Verwaltung von Magnesia, Referals, Zahlungen & Abonnements;\n"
        "- Erfüllung gesetzlicher Verpflichtungen.\n"
        "8.4. Daten werden *nicht* verkauft oder an Werbepartner weitergegeben. Zugriff ist nur autorisierten Personen "
        "oder rechtlichen Anfragen gestattet.\n"
        "8.5. Bei Profil Löschung werden primäre Profildaten innerhalb angemessener Zeit gelöscht oder anonymisiert. "
        "Bestimmte Kategorien können jedoch länger oder unbegrenzt gespeichert werden, wenn rechtlich zulässig und "
        "für die Plattform notwendig, z. B.:\n"
        "- Meldungen, Verstoßhistorie, Sperren;\n"
        "- Magnesia-Historie, Referals, Käufe & interne Abonnements;\n"
        "- technische Logs für Sicherheit & Missbrauchsprävention;\n"
        "- Chat-Fragmente im Zusammenhang mit Meldungen.\n"
        "Dies dient dem Schutz der Plattform, der Nutzer und der Verhinderung wiederholter Verstöße.\n"
        "8.6. Die Plattform speichert keine Zahlungsdaten; Zahlungen werden von Telegram verarbeitet.\n\n"

        "*9. Virtuelle Magnesia*\n"
        "9.1. Die Plattform verwendet die virtuelle Einheit „Magnesia“.\n"
        "9.2. Magnesia:\n"
        "- ist kein elektronisches Geld oder Finanzinstrument;\n"
        "- hat keinen Wert außerhalb der Plattform;\n"
        "- kann nicht ausgezahlt, verkauft oder umgewandelt werden;\n"
        "- kann nur für Plattformfunktionen genutzt werden.\n"
        "9.3. Die Verwaltung darf Regeln ändern und Salden anpassen bei Fehlern oder Missbrauch.\n\n"

        "*10. Telegram Stars, kostenpflichtige Funktionen & keine Rückerstattungen*\n"
        "10.1. Einige Funktionen können über Telegram Stars bezahlt werden.\n"
        "10.2. Stars werden über Telegram oder dessen Partner erworben; die Plattform speichert keine Finanzdaten.\n"
        "10.3. Die Abbuchung von Stars ist *endgültig und nicht erstattungsfähig*. Es gibt keinerlei Rückerstattungen "
        "— auch nicht bei Profil Löschung, Sperren, Funktionsänderungen, Telegram-Problemen oder Schließung der Plattform.\n"
        "10.4. Kostenpflichtige Funktionen gelten als bereitgestellt, sobald sie aktiviert wurden.\n\n"

        "*11. Moderation, Meldungen & Sanktionen*\n"
        "11.1. Nutzer können Verstöße über die integrierten Meldetools einreichen.\n"
        "11.2. Die Verwaltung darf beliebige Maßnahmen anwenden: Warnungen, Such-Isolation, Funktionsbeschränkungen, "
        "Sperren, Profil Löschung.\n"
        "11.3. Meldungen, Verstöße, Sperren und relevante Chat-Fragmente können unbegrenzt gespeichert werden, wenn "
        "rechtlich zulässig.\n"
        "11.4. Die Verwaltung ist nicht verpflichtet, interne Moderationslogik offenzulegen.\n\n"

        "*12. Haftungsbeschränkung*\n"
        "12.1. Die Plattform wird \"wie besehen\" („as is“) ohne Garantien bereitgestellt.\n"
        "12.2. Maximale gesetzliche Haftungsbeschränkung: keine Verantwortung für\n"
        "- direkte oder indirekte Schäden, Daten- oder Gewinnverlust;\n"
        "- Verhalten anderer Nutzer online/offline;\n"
        "- Richtigkeit von Nutzerangaben;\n"
        "- Telegram-Ausfälle;\n"
        "- Entscheidungen basierend auf Plattforminformationen.\n\n"

        "*13. Änderungen der Vereinbarung*\n"
        "13.1. Die Verwaltung kann diese Vereinbarung jederzeit aktualisieren.\n"
        "13.2. Die aktualisierte Version kann im Bot angezeigt werden. Fortgesetzte Nutzung bedeutet Zustimmung.\n"
        "13.3. Bei Nichtzustimmung müssen Sie die Nutzung beenden und Ihr Profil löschen.\n\n"

        "*14. Anwendbares Recht & Streitigkeiten*\n"
        "14.1. Es kann das Recht des Landes gelten, in dem sich die Verwaltung befindet, oder anderes anwendbares Recht.\n"
        "14.2. Streitigkeiten sind zunächst gütlich zu lösen. Falls nicht möglich, entscheidet das zuständige Gericht "
        "der Jurisdiktion der Verwaltung, sofern zwingendes Recht nichts anderes vorsieht.\n\n"

        "*15. Kontakt*\n"
        "Alle Anfragen erfolgen *ausschließlich* über den integrierten Feedback-Bereich innerhalb der Plattform. "
        "Andere Kontaktwege werden möglicherweise nicht bearbeitet.\n"
    )
}
